export { Header } from './Header'
export { Question } from './Question'
export { SelectQuestionAmount } from './SelectQuestionAmount/SelectQuestionAmount'
export { StartQuiz } from './StartQuiz'
export { Score } from './Score'
export { QuizForm } from './QuizForm/QuizForm'
